version: 0.2

phases:
  build:
    commands:
      - echo "Preparing index.html for S3 deployment"
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "ls -la"
      - aws s3 cp frontend/index.html s3://9223-b1-cf/index.html
