version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r lambda/requirements.txt -t dependencies/

  build:
    commands:
      - echo "Packaging LF1..."
      - mkdir build1
      - cp lambda/LF1.py build1/
      - cp -r dependencies/* build1/ || true
      - cd build1 && zip -r ../LF1.zip . && cd ..

      - echo "Packaging LF2..."
      - mkdir build2
      - cp lambda/LF2.py build2/
      - cp -r dependencies/* build2/ || true
      - cd build2 && zip -r ../LF2.zip . && cd ..

artifacts:
  files:
    - LF1.zip
    - LF2.zip
  name: backend-artifacts
